version: "2.4"
services:
  db:
   build:
     context: .
     dockerfile: ./Dockers/DB/Dockerfile
   container_name: IOGYM-DB
   ports:
       - "3307:3306"
   env_file:
        - docker.env
       
  api:
    build: 
      context: .
      dockerfile: ./Dockers/Api/Dockerfile
    volumes:
      - ./.:/App

    container_name: IOGYM-APP
    ports:
      - "8000:8000"
    command: tail -F anything
    depends_on:
      - db
  
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 173.18.0.0/16
          gateway: 173.18.0.1
