# Generated by Django 2.2.6 on 2019-10-24 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GYMCLASSES',
            fields=[
                ('gymclass_id', models.AutoField(primary_key=True, serialize=False)),
                ('gymclass_name', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'db_table': 'GYMCLASSES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HOURS',
            fields=[
                ('hour_id', models.AutoField(primary_key=True, serialize=False)),
                ('hour_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'HOURS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MEMBERSHIPS',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_date', models.DateField()),
                ('expiration_date', models.DateField()),
            ],
            options={
                'db_table': 'MEMBERSHIPS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TRAINERS',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(blank=True, max_length=40)),
                ('trainer_surname', models.CharField(blank=True, max_length=40, null=True)),
                ('trainer_birthday', models.DateField()),
                ('trainer_phone', models.IntegerField(blank=True, null=True)),
                ('trainer_email', models.CharField(blank=True, max_length=40, null=True)),
                ('trainer_gender', models.CharField(blank=True, max_length=1, null=True)),
                ('trainer_address', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'TRAINNERS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WEEKDAYS',
            fields=[
                ('weekdays_id', models.AutoField(primary_key=True, serialize=False)),
                ('weekdays_name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'WEEKDAYS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GROUPS',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('gymclass_id', models.ForeignKey(blank=True, db_column='gymclass_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.GYMCLASSES')),
                ('hour_id', models.ForeignKey(blank=True, db_column='hour_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.HOURS')),
                ('trainer_id', models.ForeignKey(blank=True, db_column='trainer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.TRAINERS')),
                ('weekday_id', models.ForeignKey(blank=True, db_column='weekdays_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.WEEKDAYS')),
            ],
            options={
                'db_table': 'GROUPS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CLIENTS',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=40)),
                ('client_surname', models.CharField(blank=True, max_length=40, null=True)),
                ('client_birthday', models.DateField()),
                ('client_phone', models.IntegerField(blank=True, null=True)),
                ('clietn_emergency_phone', models.IntegerField(blank=True)),
                ('client_email', models.CharField(blank=True, max_length=40, null=True)),
                ('client_gender', models.CharField(blank=True, max_length=1, null=True)),
                ('membership_id', models.ForeignKey(blank=True, db_column='membership_id', on_delete=django.db.models.deletion.DO_NOTHING, to='clients.MEMBERSHIPS')),
            ],
            options={
                'db_table': 'CLIENTS',
                'managed': True,
            },
        ),
    ]
