# Generated by Django 3.0.6 on 2020-08-26 09:02

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFL3M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.IntegerField(db_column='monday')),
                ('tuesday', models.IntegerField(db_column='tuesday')),
                ('wednesday', models.IntegerField(db_column='wednesday')),
                ('thursday', models.IntegerField(db_column='thursday')),
                ('friday', models.IntegerField(db_column='friday')),
                ('saturday', models.IntegerField(db_column='saturday')),
                ('sunday', models.IntegerField(db_column='sunday')),
            ],
            options={
                'db_table': 'CFL3M',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CFL6M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.IntegerField(db_column='monday')),
                ('tuesday', models.IntegerField(db_column='tuesday')),
                ('wednesday', models.IntegerField(db_column='wednesday')),
                ('thursday', models.IntegerField(db_column='thursday')),
                ('friday', models.IntegerField(db_column='friday')),
                ('saturday', models.IntegerField(db_column='saturday')),
                ('sunday', models.IntegerField(db_column='sunday')),
            ],
            options={
                'db_table': 'CFL6M',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CFLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.IntegerField(db_column='monday')),
                ('tuesday', models.IntegerField(db_column='tuesday')),
                ('wednesday', models.IntegerField(db_column='wednesday')),
                ('thursday', models.IntegerField(db_column='thursday')),
                ('friday', models.IntegerField(db_column='friday')),
                ('saturday', models.IntegerField(db_column='saturday')),
                ('sunday', models.IntegerField(db_column='sunday')),
            ],
            options={
                'db_table': 'CFLM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CFLY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.IntegerField(db_column='monday')),
                ('tuesday', models.IntegerField(db_column='tuesday')),
                ('wednesday', models.IntegerField(db_column='wednesday')),
                ('thursday', models.IntegerField(db_column='thursday')),
                ('friday', models.IntegerField(db_column='friday')),
                ('saturday', models.IntegerField(db_column='saturday')),
                ('sunday', models.IntegerField(db_column='sunday')),
            ],
            options={
                'db_table': 'CFLY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CFLYM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.IntegerField(db_column='records')),
                ('month_number', models.IntegerField(db_column='month_number')),
                ('year', models.IntegerField(db_column='year')),
            ],
            options={
                'db_table': 'CFLYM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='clientesView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'db_table': 'clientesView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.IntegerField(db_column='clients', verbose_name='Clientes')),
                ('trainers', models.IntegerField(db_column='trainers', verbose_name='Entrenadores')),
                ('groups', models.IntegerField(db_column='groups', verbose_name='Grupos')),
                ('classes', models.IntegerField(db_column='classes', verbose_name='Clases')),
                ('active_memberships', models.IntegerField(db_column='active_memberships', verbose_name='Membresías Activas')),
                ('expirated_memberships', models.IntegerField(db_column='expirated_memberships', verbose_name='Membresías Expiradas.')),
            ],
            options={
                'db_table': 'GeneralStats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HCFM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.IntegerField(db_column='records')),
                ('month_number', models.IntegerField(db_column='month_number')),
                ('year', models.IntegerField(db_column='year')),
            ],
            options={
                'db_table': 'HCFM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HCLYD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.IntegerField(db_column='monday')),
                ('tuesday', models.IntegerField(db_column='tuesday')),
                ('wednesday', models.IntegerField(db_column='wednesday')),
                ('thursday', models.IntegerField(db_column='thursday')),
                ('friday', models.IntegerField(db_column='friday')),
                ('saturday', models.IntegerField(db_column='saturday')),
                ('sunday', models.IntegerField(db_column='sunday')),
            ],
            options={
                'db_table': 'HCLYD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NCLYM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.IntegerField(db_column='records')),
                ('month_number', models.IntegerField(db_column='month_number')),
                ('year', models.IntegerField(db_column='year')),
            ],
            options={
                'db_table': 'NCLYM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='trainerAttendanceView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_surname', models.CharField(db_column='trainer_surname', max_length=40, verbose_name='Apellidos')),
                ('trainer_phone', models.CharField(db_column='trainer_phone', max_length=40, verbose_name='Teléfono')),
                ('register_date', models.DateField(db_column='register_date', max_length=40, verbose_name='Fecha')),
                ('description', models.CharField(db_column='description', max_length=40, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'trainerAttendanceView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CLIENTS',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=40, verbose_name='Nombre')),
                ('client_surname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Apellidos')),
                ('client_birthday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('client_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono')),
                ('client_emergency_phone', models.CharField(blank=True, max_length=12, verbose_name='Teléfono de emergencias')),
                ('client_email', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.EmailValidator(message='Email inválido')], verbose_name='Email')),
                ('client_gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No binario')], max_length=1, null=True, verbose_name='Género')),
                ('client_medical_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Información Médica')),
            ],
            options={
                'db_table': 'CLIENTS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GYMCLASSES',
            fields=[
                ('gymclass_id', models.AutoField(primary_key=True, serialize=False)),
                ('gymclass_name', models.CharField(blank=True, max_length=40, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'GYMCLASSES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TRAINERS',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(blank=True, max_length=40, verbose_name='Nombre')),
                ('trainer_surname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Apellidos')),
                ('trainer_birthday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('trainer_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono')),
                ('trainer_emergency_phone', models.CharField(blank=True, max_length=12, verbose_name='Teléfono de emergencia')),
                ('trainer_email', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.EmailValidator(message='Email inválido')], verbose_name='Email')),
                ('trainer_gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No binario')], max_length=1, null=True, verbose_name='Género')),
                ('trainer_address', models.CharField(blank=True, max_length=60, null=True, verbose_name='Dirección')),
                ('trainer_rfc', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='RFC')),
                ('trainer_password', fernet_fields.fields.EncryptedTextField(blank=True, max_length=40, verbose_name='Contraseña')),
            ],
            options={
                'db_table': 'TRAINNERS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TRAINERS_ATTENDANCES',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('description', models.CharField(blank=True, max_length=10, verbose_name='Fecha')),
                ('trainer_id', models.ForeignKey(blank=True, db_column='trainer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='clients.TRAINERS', verbose_name='Entrenador')),
            ],
            options={
                'db_table': 'TRAINNERS_ATTENDANCES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MEMBERSHIPS',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('expiration_date', models.DateField(blank=True, choices=[(datetime.date(2020, 8, 26), 'Visita (solo hoy)'), (datetime.date(2020, 9, 2), '1 semana'), (datetime.date(2020, 9, 25), '1 mes'), (datetime.date(2020, 11, 24), '3 meses'), (datetime.date(2021, 2, 22), '6 meses'), (datetime.date(2021, 8, 26), '1 año')], default=datetime.date(2020, 8, 26), null=True, verbose_name='Duración')),
                ('client_id', models.OneToOneField(blank=True, db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='clients.CLIENTS', verbose_name='Cliente')),
                ('included_classes', models.ManyToManyField(to='clients.GYMCLASSES', verbose_name='Clases incluidas')),
            ],
            options={
                'db_table': 'MEMBERSHIPS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GROUPS',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15, unique=True, verbose_name='Día')),
                ('hour', models.CharField(max_length=10, null=True, verbose_name='Hora')),
                ('gymclass_id', models.ForeignKey(blank=True, db_column='gymclass_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.GYMCLASSES', verbose_name='Clase')),
                ('trainer_id', models.ForeignKey(blank=True, db_column='trainer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.TRAINERS', verbose_name='Entrenador')),
            ],
            options={
                'db_table': 'GROUPS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CLIENTS_ATTENDANCES',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('client_id', models.ForeignKey(blank=True, db_column='client_id', on_delete=django.db.models.deletion.DO_NOTHING, to='clients.CLIENTS', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'CLIENT_ATTENDANCES',
                'managed': True,
            },
        ),
    ]
