# Generated by Django 3.1.1 on 2020-10-01 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='weekday',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='expiration_date',
            field=models.DateField(choices=[(datetime.date(2020, 9, 30), 'Cancelado'), (datetime.date(2020, 10, 1), 'Visita (solo hoy)'), (datetime.date(2020, 10, 8), '1 semana'), (datetime.date(2020, 10, 31), '1 mes'), (datetime.date(2020, 12, 30), '3 meses'), (datetime.date(2021, 3, 30), '6 meses'), (datetime.date(2021, 10, 1), '1 año')], default=datetime.date(2020, 10, 1), verbose_name='Duración'),
        ),
    ]
