# Generated by Django 2.2.6 on 2019-11-19 16:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberships',
            name='included_clsses',
        ),
        migrations.AddField(
            model_name='memberships',
            name='included_classes',
            field=models.ManyToManyField(to='clients.GYMCLASSES', verbose_name='Clases incluidas'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_birthday',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_email',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.EmailValidator(message='Email inválido')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_emergency_phone',
            field=models.BigIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1000000, message='El Numero debe ser de al menos 7 dígitos y no negativo'), django.core.validators.MaxValueValidator(9999999999, message='El Numero debe ser de máximo 10 dígitos')], verbose_name='Teléfono de emergencias'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No binario')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000, message='El Numero debe ser de al menos 7 dígitos y no negativo'), django.core.validators.MaxValueValidator(9999999999, message='El Numero debe ser de máximo 10 dígitos')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_surname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='clients_attendances',
            name='client_id',
            field=models.ForeignKey(blank=True, db_column='client_id', on_delete=django.db.models.deletion.DO_NOTHING, to='clients.CLIENTS', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='clients_attendances',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='gymclass_id',
            field=models.ForeignKey(blank=True, db_column='gymclass_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.GYMCLASSES', verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='hour_id',
            field=models.ForeignKey(blank=True, db_column='hour_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.HOURS', verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='trainer_id',
            field=models.ForeignKey(blank=True, db_column='trainer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.TRAINERS', verbose_name='Entrenador'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='weekday_id',
            field=models.ForeignKey(blank=True, db_column='weekdays_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.WEEKDAYS', verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='gymclasses',
            name='gymclass_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='hours',
            name='hour_name',
            field=models.CharField(max_length=20, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='client_id',
            field=models.OneToOneField(blank=True, db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='clients.CLIENTS', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='expiration_date',
            field=models.DateField(blank=True, choices=[(datetime.date(2019, 11, 19), 'Visita (solo hoy)'), (datetime.date(2019, 11, 26), '1 semana'), (datetime.date(2019, 12, 19), '1 mes'), (datetime.date(2020, 2, 17), '3 meses'), (datetime.date(2020, 5, 17), '6 meses'), (datetime.date(2020, 11, 18), '1 año')], null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='register_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_address',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_birthday',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_email',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.EmailValidator(message='Email inválido')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_emergency_phone',
            field=models.BigIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1000000, message='El Numero debe ser de al menos 7 dígitos y no negativo'), django.core.validators.MaxValueValidator(9999999999, message='El Numero debe ser de máximo 10 dígitos')], verbose_name='Teléfono de emergencia'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No binario')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_password',
            field=models.CharField(blank=True, max_length=40, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000, message='El Numero debe ser de al menos 7 dígitos y no negativo'), django.core.validators.MaxValueValidator(9999999999, message='El Numero debe ser de máximo 10 dígitos')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_rfc',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_surname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='trainers_attendances',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='trainers_attendances',
            name='description',
            field=models.CharField(blank=True, max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='trainers_attendances',
            name='trainer_id',
            field=models.ForeignKey(blank=True, db_column='trainer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='clients.TRAINERS', verbose_name='Entrenador'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='weekdays_name',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15, unique=True, verbose_name='Día'),
        ),
    ]
