# Generated by Django 2.2.6 on 2019-11-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberships',
            old_name='included_clsses',
            new_name='included_classes',
        ),
    ]
