# Generated by Django 2.2.6 on 2019-10-29 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEMBERSHIP_TYPES',
            fields=[
                ('membership_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'MEMBERSHIP_TYPES',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='clietn_emergency_phone',
            new_name='client_emergency_phone',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='membership_id',
        ),
        migrations.AddField(
            model_name='memberships',
            name='client_id',
            field=models.ForeignKey(blank=True, db_column='client_id', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.CLIENTS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='trainer_emergency_phone',
            field=models.IntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='trainer_password',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='trainers',
            name='trainer_rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='TRAINERS_ATTENDANCES',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=10)),
                ('trainer_id', models.ForeignKey(blank=True, db_column='client_id', on_delete=django.db.models.deletion.DO_NOTHING, to='clients.CLIENTS')),
            ],
            options={
                'db_table': 'TRAINNERS_ATTENDANCES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CLIENTS_ATTENDANCES',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('client_id', models.ForeignKey(blank=True, db_column='client_id', on_delete=django.db.models.deletion.DO_NOTHING, to='clients.CLIENTS')),
            ],
            options={
                'db_table': 'CLIENT_ATTENDANCES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CLASS_TYPES',
            fields=[
                ('class_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('gymclass_id', models.ForeignKey(blank=True, db_column='gymclass_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.GYMCLASSES')),
                ('membership_type_id', models.ForeignKey(blank=True, db_column='membership_type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='clients.MEMBERSHIP_TYPES')),
            ],
            options={
                'db_table': 'CLASS_TYPES',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='memberships',
            name='membership_type_id',
            field=models.ForeignKey(blank=True, db_column='membership_type_id', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.MEMBERSHIP_TYPES'),
            preserve_default=False,
        ),
    ]
