# Generated by Django 2.2.6 on 2019-10-31 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20191029_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_attendances',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainers_attendances',
            name='trainer_id',
            field=models.ForeignKey(blank=True, db_column='trainer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='clients.TRAINERS'),
        ),
    ]
