# Generated by Django 3.1.1 on 2020-10-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20201004_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='rfid_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Llave de acceso'),
        ),
    ]
