# Generated by Django 2.2.6 on 2019-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20191113_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberships',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Duración'),
        ),
    ]
