# Generated by Django 3.1.1 on 2020-10-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20201004_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='rfid_id',
            new_name='client_rfid',
        ),
    ]
