# Generated by Django 3.1.1 on 2020-10-06 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20201004_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientAttendanceView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('client_surname', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('date', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'db_table': 'clientAttendanceView',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='clientesView',
        ),
        migrations.AddField(
            model_name='trainers',
            name='trainer_rfid',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Llave de acceso'),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='expiration_date',
            field=models.DateField(choices=[(datetime.date(2020, 10, 5), 'Cancelado'), (datetime.date(2020, 10, 6), 'Visita (solo hoy)'), (datetime.date(2020, 10, 13), '1 semana'), (datetime.date(2020, 11, 5), '1 mes'), (datetime.date(2021, 1, 4), '3 meses'), (datetime.date(2021, 4, 4), '6 meses'), (datetime.date(2021, 10, 6), '1 año')], default=datetime.date(2020, 10, 6), verbose_name='Duración'),
        ),
    ]
