#Maria db docker file for the proyect IOGYM
#Made by Sergio Antonio Becerra Cobian 26/08/2020
#Made for docker 19.03
From mariadb:latest
#CHANGE THE PASSWORD HERE!!! the default password its in the repository so its very insecure
#Env MYSQL_ROOT_PASSWORD=eventosudg

